from fastapi import APIRouter, Depends, HTTPException, Response
from middleware.auth import get_current_user
from services.supabase_client import supabase
import io
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
import datetime

router = APIRouter(prefix="/reports", tags=["reports"])

@router.get("/")
def get_user_reports(user_id: str = Depends(get_current_user)):
    response = supabase.table("reports").select("*, uploads(image_url)").eq("user_id", user_id).order("created_at", desc=True).execute()
    return response.data

@router.get("/{report_id}")
def get_report(report_id: str, user_id: str = Depends(get_current_user)):
    response = supabase.table("reports").select("*, uploads(image_url)").eq("id", report_id).eq("user_id", user_id).execute()
    if not response.data:
        raise HTTPException(status_code=404, detail="Report not found")
    return response.data[0]

@router.get("/{report_id}/pdf")
def download_report_pdf(report_id: str, user_id: str = Depends(get_current_user)):
    response = supabase.table("reports").select("*").eq("id", report_id).eq("user_id", user_id).execute()
    if not response.data:
        raise HTTPException(status_code=404, detail="Report not found")
        
    report = response.data[0]
    
    # Generate PDF in memory
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    
    # Draw PDF
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, 750, "ThreadCounty Analysis Report")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, 710, f"Report ID: {report['id']}")
    c.drawString(50, 690, f"Date: {report['created_at']}")
    
    c.setStrokeColor(colors.black)
    c.line(50, 670, 550, 670)
    
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, 640, "Analysis Results")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, 610, f"Weave Type: {report['weave_type']}")
    c.drawString(50, 580, f"Warp Density: {report['warp_density']} /cm")
    c.drawString(50, 550, f"Weft Density: {report['weft_density']} /cm")
    c.drawString(50, 520, f"Quality Grade: {report['quality_grade']}")
    c.drawString(50, 490, f"AI Confidence: {report['confidence_score']}%")
    
    c.drawString(50, 450, "Notes:")
    c.drawString(50, 430, report['notes'] or "No additional notes.")
    
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 100, "Generated by ThreadCounty AI. This is a deterministic mock analysis for hackathon.")
    
    c.save()
    buffer.seek(0)
    
    headers = {
        'Content-Disposition': f'attachment; filename="threadcounty_report_{report_id}.pdf"'
    }
    
    return Response(content=buffer.getvalue(), media_type="application/pdf", headers=headers)
